export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_SENDING = 'LOAD_POSTS_SENDING';
export const LOAD_POSTS_FAILED = 'LOAD_POSTS_FAILED';
export const UPDATE_DOMAIN_URL = 'UPDATE_DOMAIN_URL';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';